### ISSUE TITLE
Meteor?

### ISSUE THREAD

**Issue by mrzafod** [2gis/Battlegis#2]
Ребята, может на следующий Meteor Meetup в Новосибирске вы поделитесь своими впечателениями?

**Comment by bisserof** [comment]
@mrzafod, можно попробовать. Когда он будет?

**Comment by mrzafod** [comment]
@bisserof, следующий MeteorDay будет вроде ближе к маю. Когда будет набор спикеров я напишу в личку. Спасибо.
PS: https://github.com/bisserof/test - это реально тестовое задание? на junior?

**Comment by bisserof** [comment]
@mrzafod, обычно этого хватает чтобы понять нужно звать человека на встречу или нет. 

Ну и в этом задании практически нет ограничений, поэтому способов и инструментов для его выполнения много.
